### ISSUE TITLE
Доработки.

### ISSUE THREAD

**Issue by nikvst** [BeetleMaster/Degtyarev#3]
https://github.com/BeetleMaster/Degtyarev/blob/e67f46f18565d1befe83450525bc115e997a25bf/Prac3/Practic3.py#L34

1. PEP8
1.1. В конце файла должна быть пустая строка
1.2. В строке документации закрывающие кавычки должны стоять на отдельной строке. А еще лучше, если перед ними будет ещё и пустая строка.  Комментарий слишком длинный, нужно переносить на несколько строк - по pep8 длина строки ограничена 79 символами. Также пробелы в начале строк 3 и 4 не нужны.

2. Конструкция with в случае открытия файлов позволяет нам не заботиться о его закрытии, но не спасает нас от исключений вроде FileNotFoundError. Возможно стоит переписать на что-то вроде
```
try:
    with open("week1.txt", "r") as f:
        data = f.read().split()
        if not data:
            raise EmptyFileException("Файл пуст")
except EmptyFileException as empty:
    print(empty)
except FileNotFoundError:
    print("Не удалось найти файл")    
else:
    for i in data:
    ...
```
Для файла на запись актуальны те же проблемы. Если файл существует, но нет прав на его чтение или запись, то выйдет необрабатываемое исключение и уронит нам программу.

**Comment by BeetleMaster** [comment]
@nikvst
